---
- name: Add unit file for Puma
  become: yes
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  # copy:
  #   src: puma.service
  #   dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
#    dest: /home/appuser/db_config
#    owner: appuser
#    group: appuser
  notify: restart puma

- name: enable puma
  systemd: name=puma enabled=yes  
